In [14]:
import pandas as pd
import numpy as np

In [15]:
data = {
    "Name":["Aman","Biswas","Chatur","Depak"],
    "Gender":list("MFFM"),
    "City":["Mumbai","Delhi","Kolkata","Pune"],
    "Salary": [10000,20000,30000,40000]
}

df = pd.DataFrame(data)
df

     Name Gender     City  Salary
0    Aman      M   Mumbai   10000
1  Biswas      F    Delhi   20000
2  Chatur      F  Kolkata   30000
3   Depak      M     Pune   40000

In [16]:
list_of_list_data = [
    ["Aman","M","Mumbai",10000],
    ["Biswas","F","Delhi",20000],
    ["Chatur","F","Kolkata",30000],
    ["Depak","M","Pune",40000]
]

df2 = pd.DataFrame(list_of_list_data)
df2

        0  1        2      3
0    Aman  M   Mumbai  10000
1  Biswas  F    Delhi  20000
2  Chatur  F  Kolkata  30000
3   Depak  M     Pune  40000

In [17]:
# we need to also give column name seperately
column_name = ["Name","Gender","City","Salary"]
df2 = pd.DataFrame(list_of_list_data,columns=column_name)
df2

     Name Gender     City  Salary
0    Aman      M   Mumbai   10000
1  Biswas      F    Delhi   20000
2  Chatur      F  Kolkata   30000
3   Depak      M     Pune   40000

#### Selecting rows and columns / Indexing

In [18]:
# df[columnName]
df["Name"]

0      Aman
1    Biswas
2    Chatur
3     Depak
Name: Name, dtype: str

In [19]:
# multiple columns selection
# you will pass a list of list

df[["Name","Gender"]]

     Name Gender
0    Aman      M
1  Biswas      F
2  Chatur      F
3   Depak      M

#### Adding new column

df[col_name] = [ColumnValue1,...,ColumnValueN]

- Note : If you give less or more values it will throw ERROR.
-        No. of Values must be equal to number of rows

In [20]:
df["New_col"] = ["Doctor","Enginer","Teacher","Scientist"]
df

     Name Gender     City  Salary    New_col
0    Aman      M   Mumbai   10000     Doctor
1  Biswas      F    Delhi   20000    Enginer
2  Chatur      F  Kolkata   30000    Teacher
3   Depak      M     Pune   40000  Scientist

#### Removing column
- df.drop("ColumnName",axis = 1)
- axis = 1 , means column
- asix = 0 , means row

df.drop("ColumnName",axis = 1)
- 👆 means find "ColumnName" in Column Axis
- if found delete it if not found throw error.
- By default value is axis=0

- There is another parameter inplace = True/False
- True  = Do updates in orignal df
- False = Do updates in a copy of df

In [21]:
df.drop("New_col",axis=1,inplace=True)
df

     Name Gender     City  Salary
0    Aman      M   Mumbai   10000
1  Biswas      F    Delhi   20000
2  Chatur      F  Kolkata   30000
3   Depak      M     Pune   40000

In [22]:
df

     Name Gender     City  Salary
0    Aman      M   Mumbai   10000
1  Biswas      F    Delhi   20000
2  Chatur      F  Kolkata   30000
3   Depak      M     Pune   40000

In [23]:
df.drop(["City","Gender"],axis=1)

     Name  Salary
0    Aman   10000
1  Biswas   20000
2  Chatur   30000
3   Depak   40000

In [24]:
# if you want to delete rows then pass rows index

df.drop(0,axis=0)

     Name Gender     City  Salary
1  Biswas      F    Delhi   20000
2  Chatur      F  Kolkata   30000
3   Depak      M     Pune   40000

In [25]:
# multiple rows
df.drop([0,1,2],axis=0)

    Name Gender  City  Salary
3  Depak      M  Pune   40000

In [26]:
df

     Name Gender     City  Salary
0    Aman      M   Mumbai   10000
1  Biswas      F    Delhi   20000
2  Chatur      F  Kolkata   30000
3   Depak      M     Pune   40000