In [1]:
import pandas as pd
import numpy as np

In [ ]:
data = {
    "Name":["Aman","Biswas","Chatur","Depak"],
    "Gender":list("MFFM"),
    "City":["Mumbai","Delhi","Kolkata","Pune"],
    "Salary": [10000,20000,30000,40000]
}

df = pd.DataFrame(data)
df

     Name Gender     City  Salary
0    Aman      M   Mumbai   10000
1  Biswas      F    Delhi   20000
2  Chatur      F  Kolkata   30000
3   Depak      M     Pune   40000

In [ ]:
# .loc[ row , column ] if column not defined then it select all rows
# loc takes lables names . if they are defined then you can pass index
# i am giving index of rows cause i not defined row labels
df.loc[0]

Name        Aman
Gender         M
City      Mumbai
Salary     10000
Name: 0, dtype: object

In [ ]:
# multiple rows
# syntax : df.loc[ [row_index,...] , [column_label,...] ]
df.loc[[0,1]]

     Name Gender    City  Salary
0    Aman      M  Mumbai   10000
1  Biswas      F   Delhi   20000

In [5]:
# just select name and gender
df.loc[[0,1],["Name","Gender"]]

     Name Gender
0    Aman      M
1  Biswas      F

#### iloc[row_index,col_index]
- iloc is same as loc but it only takes index as input 
- it does not accept row or column labels

In [6]:
df

     Name Gender     City  Salary
0    Aman      M   Mumbai   10000
1  Biswas      F    Delhi   20000
2  Chatur      F  Kolkata   30000
3   Depak      M     Pune   40000

In [7]:
df.iloc[0] # 0th row and all columns

Name        Aman
Gender         M
City      Mumbai
Salary     10000
Name: 0, dtype: object

In [8]:
df.iloc[[0,1,2]] # multiple rows all columns

     Name Gender     City  Salary
0    Aman      M   Mumbai   10000
1  Biswas      F    Delhi   20000
2  Chatur      F  Kolkata   30000

In [12]:
df.iloc[:,[1,2]] # all rows and just two columns

  Gender     City
0      M   Mumbai
1      F    Delhi
2      F  Kolkata
3      M     Pune